# Generated by Django 5.2 on 2025-04-15 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_assign_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='pastor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PASTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches', to=settings.AUTH_USER_MODEL),
        ),
    ]
