# Generated by Django 5.2 on 2025-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_church_pastor'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
