# Generated by Django 5.2 on 2025-04-23 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshiper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='baptized',
            field=models.BooleanField(default=False, verbose_name='Is Baptized'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.PositiveIntegerField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.church')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'unique_together': {('church', 'date')},
            },
        ),
    ]
