# Generated by Django 5.2 on 2025-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_worshiper_created_at_alter_worshiper_baptized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worshiper',
            old_name='baptized',
            new_name='is_baptized',
        ),
    ]
