# Generated by Django 5.2 on 2025-04-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_rename_baptized_worshiper_is_baptized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worshiper',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='baptism_date',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='photo',
        ),
    ]
