# Generated by Django 5.2 on 2025-04-23 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_remove_worshiper_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshiper',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worshiper',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worshiper',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worshiper',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worshiper',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worshipers/'),
        ),
    ]
