# Generated by Django 5.2 on 2025-04-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_worshiper_address_worshiper_baptism_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worshiper',
            options={},
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='baptism_date',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='worshiper',
            name='photo',
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worshipers', to='church.church', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='worshiper',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['is_baptized'], name='church_wors_is_bapt_34938c_idx'),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['gender'], name='church_wors_gender_876e46_idx'),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['created_at'], name='church_wors_created_4611c3_idx'),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['date_of_birth'], name='church_wors_date_of_9b2788_idx'),
        ),
    ]
