# Generated by Django 5.2 on 2025-04-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_alter_worshiper_options_remove_worshiper_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worshiper',
            options={'verbose_name': 'Worshiper', 'verbose_name_plural': 'Worshipers'},
        ),
        migrations.RemoveIndex(
            model_name='worshiper',
            name='church_wors_created_4611c3_idx',
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['email'], name='church_wors_email_2e6071_idx'),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['church'], name='church_wors_church__1543d5_idx'),
        ),
    ]
