# Generated by Django 5.2.1 on 2025-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshiper',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='worshiper',
            index=models.Index(fields=['is_deceased'], name='church_wors_is_dece_658120_idx'),
        ),
    ]
