# Generated by Django 5.2.1 on 2025-05-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_worshiper_is_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pastor_category',
            field=models.CharField(blank=True, choices=[('DEACON', 'Deacon'), ('PROBATIONARY', 'Probationary'), ('PRESBYTER', 'Presbyter')], max_length=20, null=True, verbose_name='Pastor Category'),
        ),
    ]
