# Generated by Django 5.2.1 on 2025-05-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_remove_church_pastor_church_pastors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='pastors',
        ),
        migrations.AddField(
            model_name='church',
            name='pastor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PASTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches', to=settings.AUTH_USER_MODEL),
        ),
    ]
